version: "2"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    tty: true

  api:
    depends_on:
      - db
    container_name: fast_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
