version: "2"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    tty: true

  api:
    depends_on:
      - db
    container_name: fast_api
    build: .
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
    expose:
      - 8000
    networks:
      - api_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - ${API_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
