version: '3.7'
services:
  zengo:
    container_name: charaban-hackathon-2023-aichi
    image: node:21-alpine3.17
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'