version: "3.8"
services:
  frontend:
    container_name: zengo
    build: .
    volumes:
      - ../front/dist:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ../ssl:/etc/apache2/ssl
    ports:
      - "443:443"
      - "80:80"
