version: "3.8"
services:
  frontend:
    container_name: zengo
    build: .
    volumes:
      - ../front/dist:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ../ssl/:${KEYS_DIR}/
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: ["--version"]
    volumes:
      - ../front/dist:/var/www/html
      - ../ssl/:${KEYS_DIR}/
    env_file:
      - .env
